### ISSUE TITLE
docket glob overwritten with ~zod/0v0 again

### ISSUE THREAD

**Issue by tinnus-napbus** [johnhyde/astrolabe#5]
```
> -read %x our %astrolabe da+now /desk/docket-0
  docket
[ %1
  title='Astrolabe'
  info='Your guide to the Urbit constellations'
  color=0x1f.243c
  href=[%glob base=%astrolabe glob-reference=[hash=0v0 location=[%ames ship=~zod]]]
  image=[~ 'https://raw.githubusercontent.com/johnhyde/astrolabe/main/ui/src/assets/astrolabe-tile.svg']
  version=[major=0 minor=1 patch=0]
  website='https://github.com/johnhyde/astrolabe'
  license='MIT'
]
```

**Comment by tinnus-napbus** [comment]
nvm fixed now

**Comment by johnhyde** [comment]
Yeah sorry, I'm still getting the hang of the deployment process. I should probably just switch to http globs, especially once I can figure out khan and do it in a github action or something.

**Comment by tinnus-napbus** [comment]
I'm not sure if it's possible to deploy an ames glob in less than two commits tbh. Not the best system. http globs are better imo. More annoying to create though
